export enum MESSAGE {
  CREATE_USER_DESC = 'Create User object as response',
  DONT_REGISTER_DESC = ' User cannot register... Try again!',
  INPUT_EMAIL_PASSWORD_DESC = 'input user email and password',
  RESPONSE_TOKEN_DESC = 'result Token',
  UPDATE_USER_DESC = 'Updaty User  object as response',
  USER_DONT_UPDATED_DESC = 'user cannot updated... Try again!',
  GET_ALL_USERS_LIST_DESC = 'Get all users',
  USERS_LIST_NOT_FOUND_DESC = 'users lists did not found.. try again ',
  PAGINATION_DESC = 'get page and size',
  GET_USER_BY_ID_DESC = 'get user by id ',
  USER_NOT_FOUND_DESC = 'this user is not found by id',
  USER_CHANGE_PASSWORD_DESC = 'user password successfully changed',
  USER_PASSWORD_IS_NOT_VALID = 'the user password is not valid',
  INPUT_USER_UUID_DESC = 'input user uuid',
  INPUT_USER_EMAIL_DESC = 'please input email address',
  EMAIL_IS_NOT_VALID_DESC = 'email address is not valid',
  INPUT_OLDPASSWORD_AND_NEWPASSWORD_DESC = 'please input user old and new passwords',
  INPUT_USER_DATA_DESC = 'input user data,',
  DELETE_USER_DATA_DESC = 'used data successfully deleted',
  STOP_USER_DATA_DESC = 'user data successfully stopped',
  USED_DATA_DONT_FOUND_DESC = 'user data not found',
  RESTORE_USER_DATA_DESC = 'user data successfully restored',
  RESTORE_STOPED_USER_DATA_DESC = ' the stoped user data successfully restored',
}
